Update build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -10,8 +10,6 @@ concurrency:
 jobs:
   build:
     runs-on: ubuntu-latest
-    permissions:
-      contents: write
     steps:
       - uses: actions/checkout@v4
 
@@ -23,10 +21,11 @@ jobs:
       - run: npm ci
       - run: npm run build
 
-      # commit and push changes
-      - run: git add -f dist/
-      - uses: qoomon/actions--create-commit@v1
-        with:
-          message: 'chore: build action'
-          skip-empty: true
-      - run: git push
+      # Verify that the dist/ is up-to-date
+      - run: |
+          git_diff="$(git diff --name-only dist/)"
+          if [ -n "$git_diff" ]; then
+            echo "::error::Drift detected in dist/ directory"
+            echo "$git_diff"
+            exit 1
+          fi
